services:
  heof-db:
    restart: always
    ports: []                          

  heof-redis:
    restart: always
    ports: []                          

  heof-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heof-app-prod
    restart: always
    env_file:
      - .env.prod
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
