"""add healing/component fields to spells, spell_classes and spell_races

Revision ID: 0c571ff6a50e
Revises: 62ead1ad9e84
Create Date: 2026-08-01 16:13:19.978650

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c571ff6a50e"
down_revision: Union[str, None] = "62ead1ad9e84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

HEALING_TARGET_ENUM = "healing_target"
HEALING_TARGET_VALUES = ("HP", "TEMP_HP")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    healing_target_enum = sa.Enum(*HEALING_TARGET_VALUES, name=HEALING_TARGET_ENUM)
    healing_target_enum.create(op.get_bind(), checkfirst=True)

    op.drop_column("spells", "components")

    op.add_column(
        "spells",
        sa.Column("has_verbal", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "spells",
        sa.Column("has_somatic", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "spells",
        sa.Column("has_material", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "spells",
        sa.Column("is_material_consumed", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "spells",
        sa.Column(
            "healing_target",
            sa.Enum(*HEALING_TARGET_VALUES, name=HEALING_TARGET_ENUM),
            nullable=True,
        ),
    )
    op.add_column("spells", sa.Column("healing_dice_count", sa.Integer(), nullable=True))
    op.add_column(
        "spells",
        sa.Column(
            "healing_dice_type",
            sa.Enum("D4", "D6", "D8", "D10", "D12", "D20", "D100", name="hit_dice"),
            nullable=True,
        ),
    )

    op.create_table(
        "spell_classes",
        sa.Column("spell_id", sa.Integer(), nullable=False),
        sa.Column("class_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["spell_id"], ["spells.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["class_id"], ["classes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("spell_id", "class_id"),
    )
    op.create_table(
        "spell_races",
        sa.Column("spell_id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["spell_id"], ["spells.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["race_id"], ["races.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("spell_id", "race_id"),
    )

    op.alter_column("spells", "has_verbal", server_default=None)
    op.alter_column("spells", "has_somatic", server_default=None)
    op.alter_column("spells", "has_material", server_default=None)
    op.alter_column("spells", "is_material_consumed", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("spell_races")
    op.drop_table("spell_classes")

    op.drop_column("spells", "healing_dice_type")
    op.drop_column("spells", "healing_dice_count")
    op.drop_column("spells", "healing_target")

    op.drop_column("spells", "is_material_consumed")
    op.drop_column("spells", "has_material")
    op.drop_column("spells", "has_somatic")
    op.drop_column("spells", "has_verbal")

    op.add_column(
        "spells",
        sa.Column("components", sa.String(length=100), nullable=False, server_default=""),
    )
    op.alter_column("spells", "components", server_default=None)

    healing_target_enum = sa.Enum(*HEALING_TARGET_VALUES, name=HEALING_TARGET_ENUM)
    healing_target_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ##
