"""update character spell model

Revision ID: 2bea8b331f7a
Revises: ae09bdf473f4
Create Date: 2026-08-02 18:33:00.817602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bea8b331f7a'
down_revision: Union[str, None] = 'ae09bdf473f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_spells', 'is_prepared')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_spells', sa.Column('is_prepared', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
