"""Add new models

Revision ID: 5bde518ea704
Revises: 69038c284ea4
Create Date: 2026-07-30 17:40:20.579459

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5bde518ea704"
down_revision: Union[str, None] = "69038c284ea4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backgrounds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("feature_name", sa.String(length=200), nullable=False),
        sa.Column("feature_description", sa.Text(), nullable=False),
        sa.Column("personality_traits_suggestions", sa.Text(), nullable=False),
        sa.Column("ideals_suggestions", sa.Text(), nullable=False),
        sa.Column("bonds_suggestions", sa.Text(), nullable=False),
        sa.Column("flaws_suggestions", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_homebrew", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_backgrounds_created_by_id"), "backgrounds", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_backgrounds_name"), "backgrounds", ["name"], unique=True)
    op.create_table(
        "campaigns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gm_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["gm_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campaigns_gm_id"), "campaigns", ["gm_id"], unique=False)
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "item_type",
            sa.Enum(
                "WEAPON",
                "ARMOR",
                "SHIELD",
                "POTION",
                "SCROLL",
                "WONDROUS_ITEM",
                "RING",
                "ROD",
                "STAFF",
                "WAND",
                "ADVENTURING_GEAR",
                "TOOL",
                "AMMUNITION",
                "TREASURE",
                "OTHER",
                name="item_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "rarity",
            sa.Enum("COMMON", "UNCOMMON", "RARE", "VERY_RARE", "LEGENDARY", "ARTIFACT", "NONE", name="item_rarity"),
            nullable=False,
        ),
        sa.Column("requires_attunement", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("cost_gold", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("damage_dice", sa.String(length=30), nullable=True),
        sa.Column(
            "damage_type",
            postgresql.ENUM(
                "SLASHING",
                "PIERCING",
                "BLUDGEONING",
                "ACID",
                "COLD",
                "FIRE",
                "FORCE",
                "LIGHTNING",
                "NECROTIC",
                "POISON",
                "PSYCHIC",
                "RADIANT",
                "THUNDER",
                name="damage_type",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("weapon_properties", sa.String(length=300), nullable=True),
        sa.Column("armor_class_base", sa.Integer(), nullable=True),
        sa.Column("armor_class_dex_bonus", sa.Boolean(), nullable=False),
        sa.Column("armor_class_max_dex_bonus", sa.Integer(), nullable=True),
        sa.Column("strength_requirement", sa.Integer(), nullable=True),
        sa.Column("stealth_disadvantage", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_homebrew", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_items_created_by_id"), "items", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_items_name"), "items", ["name"], unique=True)
    op.create_table(
        "background_skills",
        sa.Column("background_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["background_id"], ["backgrounds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("background_id", "skill_id"),
    )
    op.create_table(
        "class_spell_slot_progressions",
        sa.Column("class_id", sa.Integer(), nullable=False),
        sa.Column("class_level", sa.Integer(), nullable=False),
        sa.Column(
            "spell_level",
            postgresql.ENUM(
                "CANTRIP",
                "LEVEL_1",
                "LEVEL_2",
                "LEVEL_3",
                "LEVEL_4",
                "LEVEL_5",
                "LEVEL_6",
                "LEVEL_7",
                "LEVEL_8",
                "LEVEL_9",
                name="spell_level",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("slots", sa.Integer(), nullable=False),
        sa.CheckConstraint("class_level >= 1 AND class_level <= 20", name="check_progression_class_level_range"),
        sa.CheckConstraint("slots >= 0", name="check_progression_slots_nonnegative"),
        sa.ForeignKeyConstraint(["class_id"], ["classes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("class_id", "class_level", "spell_level"),
    )
    op.create_table(
        "features",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("CLASS", "SUBCLASS", "RACE", "BACKGROUND", "FEAT", "OTHER", name="feature_source_type"),
            nullable=False,
        ),
        sa.Column("class_id", sa.Integer(), nullable=True),
        sa.Column("race_id", sa.Integer(), nullable=True),
        sa.Column("background_id", sa.Integer(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("subclass_name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_homebrew", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["background_id"], ["backgrounds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["class_id"], ["classes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["race_id"], ["races.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_features_background_id"), "features", ["background_id"], unique=False)
    op.create_index(op.f("ix_features_class_id"), "features", ["class_id"], unique=False)
    op.create_index(op.f("ix_features_created_by_id"), "features", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_features_name"), "features", ["name"], unique=False)
    op.create_index(op.f("ix_features_race_id"), "features", ["race_id"], unique=False)
    op.create_table(
        "campaign_characters",
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("campaign_id", "character_id"),
    )
    op.create_table(
        "character_conditions",
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column(
            "condition",
            sa.Enum(
                "BLINDED",
                "CHARMED",
                "DEAFENED",
                "FRIGHTENED",
                "GRAPPLED",
                "INCAPACITATED",
                "INVISIBLE",
                "PARALYZED",
                "PETRIFIED",
                "POISONED",
                "PRONE",
                "RESTRAINED",
                "STUNNED",
                "UNCONSCIOUS",
                "EXHAUSTION",
                name="condition_type",
            ),
            nullable=False,
        ),
        sa.Column("exhaustion_level", sa.Integer(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "exhaustion_level IS NULL OR (exhaustion_level >= 1 AND exhaustion_level <= 6)",
            name="check_character_condition_exhaustion_level_range",
        ),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("character_id", "condition"),
    )
    op.create_table(
        "character_features",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("feature_id", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["feature_id"], ["features.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_character_features_character_id"), "character_features", ["character_id"], unique=False)
    op.create_index(op.f("ix_character_features_feature_id"), "character_features", ["feature_id"], unique=False)
    op.create_table(
        "character_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("is_equipped", sa.Boolean(), nullable=False),
        sa.Column("is_attuned", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.CheckConstraint("quantity >= 0", name="check_character_item_quantity_nonnegative"),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_character_items_character_id"), "character_items", ["character_id"], unique=False)
    op.create_index(op.f("ix_character_items_item_id"), "character_items", ["item_id"], unique=False)
    op.add_column("characters", sa.Column("background_id", sa.Integer(), nullable=True))
    op.add_column("characters", sa.Column("personality_traits", sa.Text(), nullable=False))
    op.add_column("characters", sa.Column("ideals", sa.Text(), nullable=False))
    op.add_column("characters", sa.Column("bonds", sa.Text(), nullable=False))
    op.add_column("characters", sa.Column("flaws", sa.Text(), nullable=False))
    op.create_index(op.f("ix_characters_background_id"), "characters", ["background_id"], unique=False)
    op.create_foreign_key(None, "characters", "backgrounds", ["background_id"], ["id"], ondelete="SET NULL")
    op.drop_column("characters", "feats")
    op.drop_column("characters", "inventory")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("inventory", sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column("characters", sa.Column("feats", sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "characters", type_="foreignkey")
    op.drop_index(op.f("ix_characters_background_id"), table_name="characters")
    op.drop_column("characters", "flaws")
    op.drop_column("characters", "bonds")
    op.drop_column("characters", "ideals")
    op.drop_column("characters", "personality_traits")
    op.drop_column("characters", "background_id")
    op.drop_index(op.f("ix_character_items_item_id"), table_name="character_items")
    op.drop_index(op.f("ix_character_items_character_id"), table_name="character_items")
    op.drop_table("character_items")
    op.drop_index(op.f("ix_character_features_feature_id"), table_name="character_features")
    op.drop_index(op.f("ix_character_features_character_id"), table_name="character_features")
    op.drop_table("character_features")
    op.drop_table("character_conditions")
    op.drop_table("campaign_characters")
    op.drop_index(op.f("ix_features_race_id"), table_name="features")
    op.drop_index(op.f("ix_features_name"), table_name="features")
    op.drop_index(op.f("ix_features_created_by_id"), table_name="features")
    op.drop_index(op.f("ix_features_class_id"), table_name="features")
    op.drop_index(op.f("ix_features_background_id"), table_name="features")
    op.drop_table("features")
    op.drop_table("class_spell_slot_progressions")
    op.drop_table("background_skills")
    op.drop_index(op.f("ix_items_name"), table_name="items")
    op.drop_index(op.f("ix_items_created_by_id"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_campaigns_gm_id"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(op.f("ix_backgrounds_name"), table_name="backgrounds")
    op.drop_index(op.f("ix_backgrounds_created_by_id"), table_name="backgrounds")
    op.drop_table("backgrounds")
    # ### end Alembic commands ###
