"""Update spell and class model

Revision ID: 62ead1ad9e84
Revises: ed896a68cda0
Create Date: 2026-08-01 02:01:15.969515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62ead1ad9e84"
down_revision: Union[str, None] = "ed896a68cda0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("spells", sa.Column("damage_dice_count", sa.Integer(), nullable=True))
    op.add_column(
        "spells",
        sa.Column(
            "damage_dice_type", sa.Enum("D4", "D6", "D8", "D10", "D12", "D20", "D100", name="hit_dice"), nullable=True
        ),
    )
    op.drop_column("spells", "damage_dice")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("spells", sa.Column("damage_dice", sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column("spells", "damage_dice_type")
    op.drop_column("spells", "damage_dice_count")
    # ### end Alembic commands ###
