"""remove imge path

Revision ID: 6fa86eefd557
Revises: a48de7f0f9b3
Create Date: 2026-08-21 18:33:21.123549

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6fa86eefd557"
down_revision: Union[str, None] = "a48de7f0f9b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "image_path")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("image_path", sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
