"""add feats and character feats

Revision ID: 44caee54d6b8
Revises: 4b17bc9bfef5
Create Date: 2026-08-02 19:28:57.387665

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "44caee54d6b8"
down_revision: Union[str, None] = "4b17bc9bfef5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ability_score_enum = postgresql.ENUM(
    "STR",
    "DEX",
    "CON",
    "INT",
    "WIS",
    "CHA",
    name="ability_score",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("prerequisite_ability", ability_score_enum, nullable=True),
        sa.Column("prerequisite_minimum_score", sa.Integer(), nullable=True),
        sa.Column("prerequisite_description", sa.Text(), nullable=False),
        sa.Column("is_homebrew", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feats_created_by_id"), "feats", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_feats_name"), "feats", ["name"], unique=True)
    op.create_table(
        "feat_ability_score_increases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("feat_id", sa.Integer(), nullable=False),
        sa.Column("ability", ability_score_enum, nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["feat_id"], ["feats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feat_ability_score_increases_feat_id"), "feat_ability_score_increases", ["feat_id"], unique=False
    )
    op.create_table(
        "character_feats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("feat_id", sa.Integer(), nullable=False),
        sa.Column("ability_score_increase_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ability_score_increase_id"], ["feat_ability_score_increases.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["feat_id"], ["feats.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_character_feats_ability_score_increase_id"),
        "character_feats",
        ["ability_score_increase_id"],
        unique=False,
    )
    op.create_index(op.f("ix_character_feats_character_id"), "character_feats", ["character_id"], unique=False)
    op.create_index(op.f("ix_character_feats_feat_id"), "character_feats", ["feat_id"], unique=False)
    op.add_column("features", sa.Column("feat_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_features_feat_id"), "features", ["feat_id"], unique=False)
    op.create_foreign_key("fk_features_feat_id_feats", "features", "feats", ["feat_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_features_feat_id_feats", "features", type_="foreignkey")
    op.drop_index(op.f("ix_features_feat_id"), table_name="features")
    op.drop_column("features", "feat_id")
    op.drop_index(op.f("ix_character_feats_feat_id"), table_name="character_feats")
    op.drop_index(op.f("ix_character_feats_character_id"), table_name="character_feats")
    op.drop_index(op.f("ix_character_feats_ability_score_increase_id"), table_name="character_feats")
    op.drop_table("character_feats")
    op.drop_index(op.f("ix_feat_ability_score_increases_feat_id"), table_name="feat_ability_score_increases")
    op.drop_table("feat_ability_score_increases")
    op.drop_index(op.f("ix_feats_name"), table_name="feats")
    op.drop_index(op.f("ix_feats_created_by_id"), table_name="feats")
    op.drop_table("feats")
    # ### end Alembic commands ###
