"""add new role of user

Revision ID: 8e6cbf5381ba
Revises: d4c1e9b2a7f3
Create Date: 2026-08-08 13:18:56.624162

"""

import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e6cbf5381ba"
down_revision: Union[str, None] = "d4c1e9b2a7f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _add_enum_value_in_autocommit(enum_name: str, value: str) -> None:
    """Add a value to a Postgres enum outside the migration transaction.

    PostgreSQL >= 12 rejects using a freshly added enum value within the same
    transaction that ran ``ALTER TYPE ... ADD VALUE``, so run it on a separate
    autocommit connection.
    """
    bind = op.get_bind()
    autocommit_conn = bind.engine.connect()
    autocommit_conn = autocommit_conn.execution_options(isolation_level="AUTOCOMMIT")
    with autocommit_conn:
        autocommit_conn.execute(sa.text(f"ALTER TYPE {enum_name} ADD VALUE IF NOT EXISTS '{value}'"))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_character_feat", "character_feats", ["character_id", "feat_id"])
    # ### end Alembic commands ###

    # Add the found_father value to the native user_role enum type (currently
    # only GM/PLAYER). Without it, no user could ever hold the founder role.
    _add_enum_value_in_autocommit("user_role", "FOUND_FATHER")

    # Promote the seeded default admin (role GM) to found father. Otherwise the
    # role is unreachable: only a found father may create/promote other found
    # fathers and delete catalog records.
    admin_login = os.getenv("ADMIN_LOGIN")
    if admin_login:
        op.execute(sa.text("UPDATE users SET role = 'FOUND_FATHER' WHERE email = :email").bindparams(email=admin_login))


def downgrade() -> None:
    """Downgrade schema."""
    # PostgreSQL has no ALTER TYPE ... DROP VALUE, so the FOUND_FATHER enum
    # value stays; only the admin promotion is reverted.
    admin_login = os.getenv("ADMIN_LOGIN")
    if admin_login:
        op.execute(sa.text("UPDATE users SET role = 'GM' WHERE email = :email").bindparams(email=admin_login))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_character_feat", "character_feats", type_="unique")
    # ### end Alembic commands ###
