"""Update character model

Revision ID: a48de7f0f9b3
Revises: b7c2d9e4f1a8
Create Date: 2026-08-21 18:32:04.426037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a48de7f0f9b3'
down_revision: Union[str, None] = 'b7c2d9e4f1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'spell_ability')
    op.drop_column('characters', 'traits')
    op.drop_column('characters', 'initiative_bonus')
    op.drop_column('characters', 'passive_perception_bonus')
    op.drop_column('characters', 'proficiencies')
    op.drop_column('characters', 'hit_dice')
    op.drop_column('characters', 'spell_attack_misc_bonus')
    op.drop_column('characters', 'has_jack_of_all_trades')
    op.drop_column('characters', 'spell_dc_misc_bonus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('spell_dc_misc_bonus', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('has_jack_of_all_trades', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('spell_attack_misc_bonus', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('hit_dice', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('proficiencies', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('passive_perception_bonus', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('initiative_bonus', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('traits', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('spell_ability', postgresql.ENUM('STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA', name='ability_score'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
