"""add subclass feature subclass id

Revision ID: a89aff41cc17
Revises: c3f8e2a1b5d9
Create Date: 2026-08-08 17:58:57.695154

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a89aff41cc17"
down_revision: Union[str, None] = "c3f8e2a1b5d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subclasses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("class_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("archetype_group_name", sa.String(length=100), nullable=True),
        sa.Column("unlock_level", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_homebrew", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["class_id"], ["classes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("class_id", "name", name="uq_subclass_class_id_name"),
    )
    op.create_index(op.f("ix_subclasses_class_id"), "subclasses", ["class_id"], unique=False)
    op.create_index(op.f("ix_subclasses_created_by_id"), "subclasses", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_subclasses_name"), "subclasses", ["name"], unique=False)
    op.add_column("features", sa.Column("subclass_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_features_subclass_id"), "features", ["subclass_id"], unique=False)
    op.create_foreign_key(
        "fk_features_subclass_id_subclasses", "features", "subclasses", ["subclass_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_features_subclass_id_subclasses", "features", type_="foreignkey")
    op.drop_index(op.f("ix_features_subclass_id"), table_name="features")
    op.drop_column("features", "subclass_id")
    op.drop_index(op.f("ix_subclasses_name"), table_name="subclasses")
    op.drop_index(op.f("ix_subclasses_created_by_id"), table_name="subclasses")
    op.drop_index(op.f("ix_subclasses_class_id"), table_name="subclasses")
    op.drop_table("subclasses")
    # ### end Alembic commands ###
