"""update damage dice for attack & item like spells

Revision ID: ad86e093f8cb
Revises: 0c571ff6a50e
Create Date: 2026-08-01 17:11:50.323540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad86e093f8cb'
down_revision: Union[str, None] = '0c571ff6a50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attacks', sa.Column('damage_dice_count', sa.Integer(), nullable=True))
    op.add_column('attacks', sa.Column('damage_dice_type', sa.Enum('D4', 'D6', 'D8', 'D10', 'D12', 'D20', 'D100', name='hit_dice'), nullable=True))
    op.drop_column('attacks', 'damage_dice')
    op.add_column('items', sa.Column('damage_dice_count', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('damage_dice_type', sa.Enum('D4', 'D6', 'D8', 'D10', 'D12', 'D20', 'D100', name='hit_dice'), nullable=True))
    op.drop_column('items', 'damage_dice')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('damage_dice', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('items', 'damage_dice_type')
    op.drop_column('items', 'damage_dice_count')
    op.add_column('attacks', sa.Column('damage_dice', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('attacks', 'damage_dice_type')
    op.drop_column('attacks', 'damage_dice_count')
    # ### end Alembic commands ###
