"""add character_ability_scores cache table

Revision ID: ae09bdf473f4
Revises: 44caee54d6b8
Create Date: 2026-08-02 17:55:51.825027

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae09bdf473f4"
down_revision: Union[str, None] = "44caee54d6b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_ability_scores",
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("strength_total", sa.Integer(), nullable=False),
        sa.Column("dexterity_total", sa.Integer(), nullable=False),
        sa.Column("constitution_total", sa.Integer(), nullable=False),
        sa.Column("intelligence_total", sa.Integer(), nullable=False),
        sa.Column("wisdom_total", sa.Integer(), nullable=False),
        sa.Column("charisma_total", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("character_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character_ability_scores")
    # ### end Alembic commands ###
