"""Remove homebrew flag and minore fields

Revision ID: af6347715f5e
Revises: 8a4c5d6e7f8a
Create Date: 2026-08-14 18:38:39.267530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6347715f5e'
down_revision: Union[str, None] = '8a4c5d6e7f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backgrounds', 'is_homebrew')
    op.drop_column('classes', 'is_homebrew')
    op.drop_column('feats', 'is_homebrew')
    op.drop_column('features', 'is_homebrew')
    op.drop_column('items', 'is_homebrew')
    op.drop_column('races', 'is_homebrew')
    op.drop_column('spells', 'is_homebrew')
    op.drop_column('subclasses', 'unlock_level')
    op.drop_column('subclasses', 'is_homebrew')
    op.drop_column('subraces', 'is_homebrew')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subraces', sa.Column('is_homebrew', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('subclasses', sa.Column('is_homebrew', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('subclasses', sa.Column('unlock_level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('spells', sa.Column('is_homebrew', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('races', sa.Column('is_homebrew', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('is_homebrew', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('features', sa.Column('is_homebrew', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('feats', sa.Column('is_homebrew', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('classes', sa.Column('is_homebrew', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('backgrounds', sa.Column('is_homebrew', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
