"""Drop DB by migration

Revision ID: bb20790b5a8c
Revises: 0003_add_default_gm
Create Date: 2026-07-26 16:17:57.053147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb20790b5a8c'
down_revision: Union[str, None] = '0003_add_default_gm'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### manually reordered to respect FK dependencies ###
    op.drop_index(op.f('idx_character_spells_character_id'), table_name='character_spells')
    op.drop_index(op.f('idx_character_spells_spell_id'), table_name='character_spells')
    op.drop_table('character_spells')

    op.drop_index(op.f('ix_attacks_character_id'), table_name='attacks')
    op.drop_table('attacks')

    op.drop_index(op.f('idx_character_name_trgm'), table_name='characters', postgresql_using='gin')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_owner_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_race_id'), table_name='characters')
    op.drop_table('characters')

    op.drop_index(op.f('idx_spell_level'), table_name='spells')
    op.drop_index(op.f('ix_spells_level'), table_name='spells')
    op.drop_index(op.f('ix_spells_name'), table_name='spells')
    op.drop_table('spells')

    op.drop_index(op.f('idx_race_name_trgm'), table_name='races', postgresql_using='gin')
    op.drop_index(op.f('ix_races_name'), table_name='races')
    op.drop_table('races')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('GM', 'PLAYER', name='user_role'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'player'::character varying"))
    op.create_table('races',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('races_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(length=20), server_default=sa.text("'Средний'::character varying"), autoincrement=False, nullable=False),
    sa.Column('speed', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=False),
    sa.Column('ability_bonuses', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('granted_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('traits', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('is_homebrew', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='races_pkey'),
    sa.UniqueConstraint('name', name='races_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_races_name'), 'races', ['name'], unique=True)
    op.create_index(op.f('idx_race_name_trgm'), 'races', ['name'], unique=False, postgresql_using='gin')
    op.create_table('character_spells',
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spell_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('character_spells_character_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spell_id'], ['spells.id'], name=op.f('character_spells_spell_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'spell_id', name=op.f('character_spells_pkey'))
    )
    op.create_index(op.f('idx_character_spells_spell_id'), 'character_spells', ['spell_id'], unique=False)
    op.create_index(op.f('idx_character_spells_character_id'), 'character_spells', ['character_id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('characters_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('character_class', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('subclass', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('race_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_hp', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('max_hp', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('temp_hp', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('hit_dice', sa.VARCHAR(length=20), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('speed', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=False),
    sa.Column('armor_class', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.Column('shield', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('initiative_bonus', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('passive_perception_bonus', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('has_jack_of_all_trades', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('strength', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.Column('dexterity', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.Column('constitution', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.Column('intelligence', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.Column('wisdom', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.Column('charisma', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.Column('skill_proficiencies', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('saving_throw_proficiencies', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('proficiencies', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('traits', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('feats', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('inventory', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('backstory', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('money_gold', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('money_silver', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('money_copper', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('spell_ability', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('spell_dc_misc_bonus', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('spell_attack_misc_bonus', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('spell_slots', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('current_hp >= 0', name='check_current_hp_nonnegative'),
    sa.CheckConstraint('level >= 1 AND level <= 20', name='check_character_level_range'),
    sa.CheckConstraint('max_hp >= 0', name='check_max_hp_nonnegative'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='characters_owner_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name='characters_race_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='characters_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_characters_race_id'), 'characters', ['race_id'], unique=False)
    op.create_index(op.f('ix_characters_owner_id'), 'characters', ['owner_id'], unique=False)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.create_index(op.f('idx_character_name_trgm'), 'characters', ['name'], unique=False, postgresql_using='gin')
    op.create_table('attacks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('attack_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('ability', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('is_proficient', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('bonus_attack', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('bonus_damage', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('damage_dice', sa.VARCHAR(length=30), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('damage_type', sa.VARCHAR(length=30), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('range', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('attacks_character_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('attacks_pkey'))
    )
    op.create_index(op.f('ix_attacks_character_id'), 'attacks', ['character_id'], unique=False)
    op.create_table('spells',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('school', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('cast_time', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('range_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('range_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('components', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('material', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_ritual', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('duration', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_concentration', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('attack_type', sa.VARCHAR(length=20), server_default=sa.text("'NONE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('save_stat', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('damage_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('damage_dice', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('higher_levels', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('spells_pkey')),
    sa.UniqueConstraint('name', name=op.f('spells_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_spells_name'), 'spells', ['name'], unique=True)
    op.create_index(op.f('ix_spells_level'), 'spells', ['level'], unique=False)
    op.create_index(op.f('idx_spell_level'), 'spells', ['level'], unique=False)
    # ### end Alembic commands ###