"""Update class with hit dice enum

Revision ID: ed896a68cda0
Revises: 5bde518ea704
Create Date: 2026-07-31 18:45:33.978615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed896a68cda0'
down_revision: Union[str, None] = '5bde518ea704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'hit_dice',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('D4', 'D6', 'D8', 'D10', 'D12', 'D20', 'D100', name='hit_dice'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'hit_dice',
               existing_type=sa.Enum('D4', 'D6', 'D8', 'D10', 'D12', 'D20', 'D100', name='hit_dice'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
